 
FROM debian:buster-20190708

RUN apt-get update && apt-get install -y libicu63 socat wget curl

RUN useradd -m helium

COPY helium /helium/

RUN mkdir /sdk/ && chown -R helium:helium /sdk/ /helium/

USER helium

WORKDIR /work

ENTRYPOINT ["/helium/launch.sh"]
