[[repo.maven]]
name = "maven-central"
url = "https://repo1.maven.org/maven2/"

[[repo.nuget]]
name = "NuGet.org"
url = "https://api.nuget.org/v3/index.json"

[repo.npm]
registry = "https://registry.npmjs.com"

