FROM openjdk:11.0.4-jdk-stretch as build

RUN apt-get update && apt-get install -y build-essential

RUN useradd -m helium && \
	mkdir -p /helium-src/ && \
	mkdir -p /docker-launcher/ && \
	mkdir -p /tools/ && \
	chown -R helium:helium /helium-src/ /docker-launcher/ /tools/

USER helium

WORKDIR /tools/
RUN wget https://piccolo.link/sbt-1.3.2.tgz && tar xf sbt-1.3.2.tgz

ENV PATH "/tools/sbt/bin:${PATH}"

WORKDIR /helium-src/
COPY --chown=helium:helium src /helium-src/src/
COPY --chown=helium:helium build.sbt /helium-src/build.sbt
COPY --chown=helium:helium project /helium-src/project/

RUN sbt assembly

WORKDIR /docker-launcher/
COPY --chown=helium:helium docker/helium-engine/linux/docker-launcher /docker-launcher/

RUN gcc --std=c99 -D_POSIX_C_SOURCE=200809L -o docker-launcher docker-launcher.c

