#include "Dockerfile.build.in"

FROM openjdk:11.0.4-jdk-stretch

RUN apt-get update && \
	apt-get install -y libicu57 sudo && \
	useradd -m helium && \
	mkdir -p /helium/cache/ && \
	chown helium:helium /helium/cache/

#include "Dockerfile.install.in"

USER root

ENTRYPOINT ["/helium/bin/helium-bootstrap"]
