#include "Dockerfile.build.in"

FROM debian:buster-20190708

RUN apt-get update && \
	apt-get install -y libicu63 libssl1.1 ca-certificates && \
	useradd -m helium && \
	mkdir -p /helium/cache/ && \
	chown helium:helium /helium/cache/

#include "Dockerfile.install.in"

USER helium
