FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

RUN useradd -m helium

USER helium

COPY --chown=helium:helium src /src/
WORKDIR /src/Engine/
RUN dotnet publish -c Release -r linux-x64 --self-contained true

WORKDIR /src/JobExecutor/
RUN dotnet publish -c Release -r linux-x64 --self-contained true

#ifdef INCLUDE_AGENT
WORKDIR /src/CI.Agent/
RUN dotnet publish -c Release -r linux-x64 --self-contained true
#endif
