FROM mcr.microsoft.com/dotnet/core/sdk:3.0 as build

RUN useradd -m helium && \
	mkdir -p /helium-src/ && \
	mkdir -p /docker-launcher/ && \
	mkdir -p /tools/ && \
	chown -R helium:helium /helium-src/ /docker-launcher/ /tools/

USER helium

COPY --chown=helium:helium src /src/
WORKDIR /src/Engine/
RUN dotnet publish -c Release -r linux-x64 --self-contained true

WORKDIR /src/JobExecutor/
RUN dotnet publish -c Release -r linux-x64 --self-contained true

