#include "Dockerfile.build.in"

FROM openjdk:11.0.4-jdk-stretch

RUN apt-get update && \
	apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
	curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
	add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
	apt-get update && \
	apt-get install -y docker-ce-cli socat sudo && \
	useradd -m helium && \
	mkdir -p /helium/cache/ && \
	chown helium:helium /helium/cache/

#include "Dockerfile.install.in"

USER root

ENTRYPOINT ["/helium/bin/helium-bootstrap"]