#include "../../helium-engine/linux/Dockerfile.build.in"

FROM jenkins/jnlp-slave:3.35-5-jdk11

USER root

RUN apt-get update && \
	apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
	curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
	add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
	apt-get update && \
	apt-get install -y docker-ce-cli socat sudo && \
	mkdir -p /helium/cache/ && \
	chown jenkins:jenkins /helium/cache/

#include "../../helium-engine/linux/Dockerfile.install.in"

COPY --chown=root:root docker/jenkins-slave/linux/helium/ /helium/

USER root

ENTRYPOINT ["/helium/bin/helium-bootstrap"]
