#include "../../helium-engine/linux/Dockerfile.build.in"

FROM jenkins/jnlp-slave:3.35-5-jdk11

USER root

RUN apt-get update && \
	apt-get install -y libicu57 sudo && \
	mkdir -p /helium/cache/ && \
	chown jenkins:jenkins /helium/cache/

#include "../../helium-engine/linux/Dockerfile.install.in"

COPY --chown=root:root docker/jenkins-slave/linux/helium/ /helium/

USER root

ENTRYPOINT ["/helium/bin/helium-bootstrap"]
